/*---------------------------------------------------------------------------
 * FILE: AddCustDlg.h
 *
 * Description:
 * ATL Dlg class, most code are generated by VC, only 4 new methods
 * have been added:
 *
 *  OnClickedSubmit()
 *  OnClickedView_req()
 *  OnClickedView_res()
 *  OnClickedExit()
 *
 *
 * This application allows user to enter a new customer name and contact
 * information, such as first name, last name, phone. It then sends the
 * qbXML request to QuickBooks via qbXMLRP COM object. It parses the response
 * from QuickBooks and displays the result. It also provides GUI to allow the user
 * to view the request/response XML, and validate the requestXML.
 *
 * Created On: 11/07/2001
 * Updated to QBXML 2.0 August 2002
 *
 *
 * Copyright © 2002-2013 Intuit Inc. All rights reserved.
 * Use is subject to the terms specified at:
 *     http://developer.intuit.com/legal/devsite_tos.html
 *
 */

#ifndef __ADDCUSTDLG_H_
#define __ADDCUSTDLG_H_

#include "resource.h"       // main symbols
#include <atlhost.h>
#include "CustomerAdd.h"

#define FIELD_SIZE 256

class CAddCustDlg :
  public CAxDialogImpl<CAddCustDlg>
  {
public:

  // Constructor
  //
  CAddCustDlg();

  // Destructor
  //
  ~CAddCustDlg();

  enum { IDD = IDD_ADDCUSTDLG };

BEGIN_MSG_MAP(CAddCustDlg)
  MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
  COMMAND_ID_HANDLER(IDOK, OnOK)
  COMMAND_ID_HANDLER(IDCANCEL, OnCancel)
  COMMAND_HANDLER(IDC_Submit, BN_CLICKED, OnClickedSubmit)
  COMMAND_HANDLER(IDC_View_Req, BN_CLICKED, OnClickedView_req)
  COMMAND_HANDLER(IDC_View_Res, BN_CLICKED, OnClickedView_res)
  COMMAND_HANDLER(IDC_Exit, BN_CLICKED, OnClickedExit)
  COMMAND_HANDLER(IDC_Browse, BN_CLICKED, OnClickedBrowse)
  //  MESSAGE_HANDLER(WM_DESTROY, OnDestroy)
  COMMAND_HANDLER(IDC_ValidateReq, BN_CLICKED, OnClickedValidateReq)
END_MSG_MAP()

  LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
  {
    // set the default company file
    SetDlgItemText(IDC_COM_FILE, (LPTSTR) InitFileName("c:\\program files\\intuit\\quickbooks pro", "sample_product-based business.qbw"));
    return 1;  // Let the system set the focus
  }

  LRESULT OnDestroy(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
  {
    DestroyWindow();
    PostQuitMessage(0);
    return 0;
  }

  LRESULT OnOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
  {
    //DestroyWindow();
    //PostQuitMessage(0);
    //EndDialog(wID);
    return 0;
  }

  LRESULT OnCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
  {
    DestroyWindow();
    PostQuitMessage(0);
    //EndDialog(wID); this is IDL generated code which will cause assert
    return 0;
  }

  // Submit Button
  LRESULT OnClickedSubmit(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);

  // View Request Button
  LRESULT OnClickedView_req(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);

  // View Response Button
  LRESULT OnClickedView_res(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);

  // Exit Button
  LRESULT OnClickedExit(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled)
  {
    DestroyWindow();
    PostQuitMessage(0);
    return 0;
  }

  // Browse Button
  LRESULT OnClickedBrowse(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);

  // Validate Result
  LRESULT OnClickedValidateReq(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);

private:
  // Create File Path
  TCHAR * InitFileName(TCHAR * szDefaultPath, TCHAR * szFileName);

  bool CollectFormData(TCHAR * szRestOfMsg);

  void ReplaceChar(const string &str, string &out);

  string m_RequestXML;   // requestXML
  string m_ResponseXML;  // responseXML

  // form input data
  //

  TCHAR m_CompanyFile[FIELD_SIZE];
  TCHAR m_CustName[FIELD_SIZE];
  TCHAR m_Phone[FIELD_SIZE];
  TCHAR m_FirstName[FIELD_SIZE];
  TCHAR m_LastName[FIELD_SIZE];

  string m_Msg;

};

#endif //__ADDCUSTDLG_H_
